[tools]
rust = "1.95.0"
node = "25.7.0"
pnpm = "10.33.0"
"cargo:wasm-pack" = "0.14.0"

[tasks."ecs:ci"]
run = "cargo test --all-targets --all-features -- --nocapture"
dir = "crates/ecs"

[tasks."build:wasm"]
run = "wasm-pack build --target web --out-dir frontend/src/lib/hyakou"
dir = "crates/wasm-bindings"

[tasks."backend:ci"]
run = "RUST_LOGa=debug RUST_BACKTRACE=1 HYAKOU_RUN_GPU_TESTS=0 cargo test -p hyako --all-targets --all-features -- --nocapture"

[tasks."frontend:ci"]
run = [
"pnpm run format:check",
# "pnpm run lint",
"pnpm run test"
]
dir = "frontend"

[tasks."frontend:setup"]
run = "pnpm install"
dir = "frontend"

[tasks."frontend:serve"]
run = "pnpm run dev"
dir = "frontend"

[tasks."backend:serve"]
run = "cargo run"
dir = "crates"
