#[derive(Debug, Default, Ord, PartialOrd, Eq, PartialEq)]
pub enum Key {
    #[default]
    NONE,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    ZERO,
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    CTRL,
    ALT,
    MOD,
    OPTION,
    SHIFT,
    TAB,
    CAPSLOCK,
    ESC,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    BACKSPACE,
    SPACE,
    UP,
    DOWN,
    LEFT,
    RIGHT,
    ENTER,
    RSHIFT,
    BACKSLASH,
    DOT,
    COMMA,
    SLASH,
    #[allow(non_camel_case_types)]
    BRACKET_OPEN,
    #[allow(non_camel_case_types)]
    BRACKET_CLOSE,
    SEMICOLON,
    APOSTROPH,
    EQUALS,
    MINUS,
}

impl Key {
    pub fn convert(val: &str) -> Key {
        match val {
            // Letters
            "A" => Key::A,
            "B" => Key::B,
            "C" => Key::C,
            "D" => Key::D,
            "E" => Key::E,
            "F" => Key::F,
            "G" => Key::G,
            "H" => Key::H,
            "I" => Key::I,
            "J" => Key::J,
            "K" => Key::K,
            "L" => Key::L,
            "M" => Key::M,
            "N" => Key::N,
            "O" => Key::O,
            "P" => Key::P,
            "Q" => Key::Q,
            "R" => Key::R,
            "S" => Key::S,
            "T" => Key::T,
            "U" => Key::U,
            "V" => Key::V,
            "W" => Key::W,
            "X" => Key::X,
            "Y" => Key::Y,
            "Z" => Key::Z,

            // Numbers (as digit characters)
            "0" => Key::ZERO,
            "1" => Key::ONE,
            "2" => Key::TWO,
            "3" => Key::THREE,
            "4" => Key::FOUR,
            "5" => Key::FIVE,
            "6" => Key::SIX,
            "7" => Key::SEVEN,
            "8" => Key::EIGHT,
            "9" => Key::NINE,

            // Modifiers
            "CTRL" => Key::CTRL,
            "ALT" => Key::ALT,
            "MOD" => Key::MOD,
            "OPTION" => Key::OPTION,
            "SHIFT" => Key::SHIFT,
            "RSHIFT" => Key::RSHIFT,
            "CAPSLOCK" => Key::CAPSLOCK,

            // Function keys
            "F1" => Key::F1,
            "F2" => Key::F2,
            "F3" => Key::F3,
            "F4" => Key::F4,
            "F5" => Key::F5,
            "F6" => Key::F6,
            "F7" => Key::F7,
            "F8" => Key::F8,
            "F9" => Key::F9,
            "F10" => Key::F10,
            "F11" => Key::F11,
            "F12" => Key::F12,

            // Special keys
            "TAB" => Key::TAB,
            "ESC" => Key::ESC,
            "BACKSPACE" => Key::BACKSPACE,
            "SPACE" => Key::SPACE,
            "ENTER" => Key::ENTER,

            // Arrow keys (winit style)
            "ArrowUp" => Key::UP,
            "ArrowDown" => Key::DOWN,
            "ArrowLeft" => Key::LEFT,
            "ArrowRight" => Key::RIGHT,

            // Special characters (as symbols)
            "\\" => Key::BACKSLASH,
            "." => Key::DOT,
            "," => Key::COMMA,
            "/" => Key::SLASH,
            "[" => Key::BRACKET_OPEN,
            "]" => Key::BRACKET_CLOSE,
            ";" => Key::SEMICOLON,
            "'" => Key::APOSTROPH,
            "=" => Key::EQUALS,
            "-" => Key::MINUS,

            // Default
            _ => Key::NONE,
        }
    }
}
